---
title: "ETC5513-Assignment4"
author:
- familyname: 
  othernames: 
  address: Monash University
  email: 
  correspondingauthor: true
  qualifications:
- familyname: 
  othernames: 
  address: Monash University
  email: 
  correspondingauthor: true
  qualifications:
- familyname: 
  othernames: 
  address: Monash University
  email: 
  correspondingauthor: true
  qualifications:
- familyname: 
  othernames: 
  address: Monash University
  email: 
  correspondingauthor: true
  qualifications:
department: Department of\newline Econometrics &\newline Business Statistics
organization: Acme Corporation
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  MonashEBSTemplates::report:
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE, messages=FALSE, warning=FALSE, fig.pos = 'H')

library(tidyverse)
library(ggplot2)
library(kableExtra)
library(here)
library(ggthemes)
library(countrycode)
library(gganimate)
library(broom)
library(stargazer)

```


```{r readingdata, message = FALSE, warning = FALSE}
expectancy <- read_csv(here::here("data", "life_expectancy.csv"))
names(expectancy) <- paste(names(expectancy), expectancy[1, ], sep = "_") ## Merging first two header rows together to get row names
expectancy <- expectancy[-1,] ## Removing now unnecessary firt row

spend <- read_csv(here::here("data", "health_expenditure.csv"), skip = 1)

gdp <- read_csv(here::here("data", "gdp_data.csv"), skip = 3)

head(expectancy,10)
head(spend, 10)
head(gdp, 10)
```

```{r}
expectancy_clean <- expectancy %>%
  pivot_longer(cols = `Life expectancy at birth (years)_Both sexes`:`Healthy life expectancy (HALE) at age 60 (years)_2_Female`,
               names_to = c("Type", "Gender"),
               names_sep = "_",
               values_to = "Expectancy") %>%
  mutate(Gender = if_else(Gender == "1", "Male",
                          if_else(Gender == 2, "Female", "Both"))) %>%
  rename(Country = X1_Country,
         Year = X2_Year) %>%
  mutate(Expectancy = as.numeric(Expectancy)) %>%
  mutate(Year = as.numeric(Year))
```



\section*{Introduction}



\section*{Differences between men and women}



\section*{Life expectancy and Health expenditure}

```{r country, include=FALSE}
country_le <- expectancy_clean %>% 
  filter(Gender == "Both") %>% 
  pivot_wider(names_from = Type, 
  values_from = Expectancy)

#examine data
head(country_le)

```


```{r continent}
# Add continent variable
country_le_continent <- country_le %>% 
  mutate(continent = countrycode(sourcevar = country_le$Country, 
                                            origin = "country.name",
                                            destination = "continent")) %>% 
  mutate(Year = as.character(Year))
  
```


```{r tidy_data}
# tidy health expenditure data
health_expenditure <- spend %>% 
  select(-2) %>%   #remove year2017 to match the life expectancy data
  pivot_longer(cols = c(2:18), names_to = "Year", 
               values_to = "Health expenditure per capita(US$)") 
  
```

```{r le_hs}
# join life_expectancy and health_expenditure
life_health_expenditure <- left_join(country_le_continent, 
                               health_expenditure, 
                               by = c("Country" = "Country", 
                                      "Year" = "Year")) %>% 
  mutate(Year = as.integer(Year),
         `Health expenditure per capita(US$)` = as.numeric(`Health expenditure per capita(US$)`),
         `Life expectancy at birth (years)` = as.numeric(`Life expectancy at birth (years)`),
         `Life expectancy at age 60 (years)` = as.numeric(`Life expectancy at age 60 (years)`))

```


```{r birth, message=FALSE}
ggplot(life_health_expenditure, 
            aes(`Health expenditure per capita(US$)`, 
                `Life expectancy at birth (years)`, 
                size = `Life expectancy at birth (years)`,
                colour = continent)) +
  geom_point(alpha = 0.6,na.rm = TRUE) +
  scale_color_brewer(palette = "Set2")+
  scale_size(range = c(1, 4)) +
  transition_time(Year) +
  labs(title = 'Year: {frame_time}', 
       x = "Health expenditure per capita(US$)", 
       y = "Life expectancy at birth") +
  ease_aes()+
  theme_bw()

```


```{r age60, message=FALSE}
ggplot(life_health_expenditure, 
            aes(`Health expenditure per capita(US$)` , 
                `Life expectancy at age 60 (years)`, 
                size = `Life expectancy at birth (years)`,
                colour = continent)) +
  geom_point(alpha = 0.6,na.rm = TRUE) +
  scale_color_brewer(palette = "Set2")+
  scale_size(range = c(1, 4)) +
  transition_time(Year) +
  labs(title = 'Year: {frame_time}', 
       x = "Health expenditure per capita(US$)", 
       y = "Life expectancy at age 60") +
  ease_aes()+
  theme_bw()

```


```{r}
life_health_lm <- life_health_expenditure %>% 
  filter(!is.na(`Health expenditure per capita(US$)`)) %>% 
  filter(!is.na(`Healthy life expectancy (HALE) at birth (years)`)) %>% 
  filter(!is.na(`Healthy life expectancy (HALE) at age 60 (years)`)) %>% 
  select(-c(4:5))
  
```

```{r}
lm_birth <- lm (`Healthy life expectancy (HALE) at birth (years)` ~ `Health expenditure per capita(US$)`, life_health_lm)

```


```{r}
tidy(lm_birth)
```

```{r}
glance(lm_birth)
```

```{r}
birth_aug <- augment(lm_birth, life_health_lm)

```


```{r}
ggplot(birth_aug, 
       aes(x = `Health.expenditure.per.capita.US..`, 
           y = .fitted)) + 
  #geom_line(colour = "blue") + 
  geom_point(aes(x = `Health.expenditure.per.capita.US..`,
                 y = `Healthy.life.expectancy..HALE..at.birth..years.`))+
  geom_smooth(method = "lm")+
  scale_x_log10() +
  scale_y_log10() 

```



```{r}
lm_age60 <- lm (`Healthy life expectancy (HALE) at age 60 (years)` ~ `Health expenditure per capita(US$)`, life_health_lm)

```

```{r}
tidy(lm_age60)
```

```{r}
glance(lm_age60)
```

```{r}
age60_aug <- augment(lm_age60, life_health_lm)

```


```{r}
ggplot(age60_aug, 
       aes(x = `Health.expenditure.per.capita.US..`, 
           y = .fitted)) + 
  #geom_line(colour = "blue") + 
  geom_point(aes(x = `Health.expenditure.per.capita.US..`,
                 y = `Healthy.life.expectancy..HALE..at.age.60..years.`))+
  geom_smooth(method = "lm")+
  scale_x_log10() +
  scale_y_log10() 

```


\section*{Life expectancy at birth vs at 60}



\section*{Life expectancy and Gross Domestic Product}

